### ISSUE TITLE
import error in cloudacademy_dl.py

### ISSUE THREAD

**Issue by ShoaibAkhtar026** [josefeg/cloudacademy-dl#3]
trying to download https://cloudacademy.com/course/certified-developer-designing-and-developing but getting error 

```
Traceback (most recent call last):
  File "/home/shoaib/.local/bin/cloudacademy-dl", line 7, in <module>
    from cloudacademy.cloudacademy_dl import main
  File "/home/shoaib/.local/lib/python2.7/site-packages/cloudacademy/cloudacademy_dl.py", line 30, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
```
How can i fix this error?

**Comment by beraybentesen** [comment]
install via pip3 instead of pip then error will be gone. However, download process is not working for me.
